export const GET_PEOPLE_BY_SEARCH_REQUEST = "GET_PEOPLE_BY_SEARCH_REQUEST";
export const GET_PEOPLE_BY_SEARCH_SUCCESS = "GET_PEOPLE_BY_SEARCH_SUCCESS";
export const GET_PEOPLE_BY_SEARCH_FAILURE = "GET_PEOPLE_BY_SEARCH_FAILURE";

export const GET_PERSON_DETAILS_REQUEST = "GET_PERSON_DETAILS_REQUEST";
export const GET_PERSON_DETAILS_SUCCESS = "GET_PERSON_DETAILS_SUCCESS";
export const GET_PERSON_DETAILS_FAILURE = "GET_PERSON_DETAILS_FAILURE";
